(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['systemCategory_m_index'] = template({"1":function(container,depth0,helpers,partials,data) {
    var stack1;

  return ((stack1 = helpers.each.call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? depth0.managementNavigation : depth0),{"name":"each","hash":{},"fn":container.program(2, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "");
},"2":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "                <tr>\n                    <th scope=\"row\">"
    + alias4(((helper = (helper = helpers.index || (data && data.index)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"index","hash":{},"data":data}) : helper)))
    + "</th>\n                    <td>"
    + alias4(((helper = (helper = helpers.mLevelOneName || (depth0 != null ? depth0.mLevelOneName : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"mLevelOneName","hash":{},"data":data}) : helper)))
    + "</td>\n                    <td>\n                        <button type=\"button\" class=\"btn btn-outline-warning\" data-toggle=\"modal\" data-target=\"#managementSystemCategoryModal\" onclick=\"editManagementSystemCategory('"
    + alias4(((helper = (helper = helpers.mCategoryId || (depth0 != null ? depth0.mCategoryId : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"mCategoryId","hash":{},"data":data}) : helper)))
    + "')\"><i class=\"fa fa-wrench\"></i></button>\n                    </td>\n                </tr>\n";
},"4":function(container,depth0,helpers,partials,data) {
    return "编辑";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {});

  return "<script>\n    function addLevelTwoInput() {\n        let dynamicHtml =\n            \"<div class='row' id='row\" + Date.now() + \"'>\" +\n            \"<div class='col-10'>\" +\n            \"<input type='text' class='form-control' placeholder='二级系统分类' name='levelTwoNameList'>\" +\n            \"</div>\" +\n            \"<div class='col-2 text-right'>\" +\n            \"<button type='button' class='btn btn-outline-danger' onclick=\\\"subLevelTwoInput('row\" + Date.now() + \"')\\\">\" +\n            \"<i class='fa fa-minus-circle'></i>\" +\n            \"</button>\" +\n            \"</div>\" +\n            \"</div>\";\n\n        $(\"#levelTwo_formGroup\").append(dynamicHtml);\n    }\n    function subLevelTwoInput(divId) {\n        $(\"#\" + divId).remove();\n    }\n\n    function confirmAdd() {\n        let parameter = $(\"#systemCategoryForm\").serializeObject();\n        $.ajax({\n            type: \"post\",\n            contentType:\"application/json\",\n            dataType:\"json\",\n            data: JSON.stringify(parameter),\n            url: \"http://127.0.0.1:8080/STE/addManagementCategory\",\n            success: function (result) {\n                $(\"button[data-dismiss=modal]\").trigger(\"click\");\n                alert(\"添加完成\");\n            }\n        });\n    }\n\n    function editManagementSystemCategory(mCategoryId){\n        $.ajax({\n            type:\"get\",\n            contentType:\"application/json\",\n            dataType:\"json\",\n            data: {\n                \"id\":mCategoryId\n            },\n            url:\"http://127.0.0.1:8080/STE/getManagementSystemCategoryById\",\n            success:function(result){\n                let getManagementSystemCategoryById={\n                    \"getManagementSystemCategoryById\":result\n                }\n                let dataHtml = Handlebars.templates.systemCategory_m_index(getManagementSystemCategoryById);\n                $(\"#v-pills-tabContent\").html(dataHtml);\n            }\n        });\n    }\n</script>\n<div class=\"row\">\n    <div class=\"col-12\">\n        <div class=\"row\">\n            <div class=\"col-6\">\n                <button type=\"button\" class=\"btn btn-outline-success\" data-toggle=\"modal\" data-target=\"#managementSystemCategoryModal\"><i\n                        class=\"fa fa-plus\"></i></button>\n            </div>\n            <div class=\"col-6 text-right\">\n                <button type=\"button\" class=\"btn btn-outline-danger\"><i class=\"fa fa-trash\"></i></button>\n            </div>\n        </div>\n\n        <table class=\"table table-bordered\">\n            <thead>\n                <tr>\n                    <th scope=\"col\">序号</th>\n                    <th scope=\"col\">一级分类名称</th>\n                    <th scope=\"col\">操作</th>\n                </tr>\n            </thead>\n            <tbody>\n"
    + ((stack1 = helpers["if"].call(alias1,(depth0 != null ? depth0.managementNavigation : depth0),{"name":"if","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "            </tbody>\n        </table>\n    </div>\n</div>\n\n<!-- Modal -->\n<div class=\"modal fade\" id=\"managementSystemCategoryModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n    aria-hidden=\"true\">\n    <div class=\"modal-dialog\" role=\"document\">\n        <div class=\"modal-content\">\n            <div class=\"modal-header\">\n                <h5 class=\"modal-title\" id=\"exampleModalLabel\">"
    + ((stack1 = helpers["if"].call(alias1,(depth0 != null ? depth0.getManagementSystemCategoryById : depth0),{"name":"if","hash":{},"fn":container.program(4, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "添加1系统分类</h5>\n                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n                    <span aria-hidden=\"true\">&times;</span>\n                </button>\n            </div>\n            <div class=\"modal-body\">\n                <form id=\"systemCategoryForm\">\n                    <div class=\"form-group\">\n                        <label for=\"exampleInputEmail1\">一级系统分类</label>\n                        <input type=\"text\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"一级系统分类\"\n                            name=\"levelOneName\" value=\""
    + container.escapeExpression(((helper = (helper = helpers.mLevelOneName || (depth0 != null ? depth0.mLevelOneName : depth0)) != null ? helper : helpers.helperMissing),(typeof helper === "function" ? helper.call(alias1,{"name":"mLevelOneName","hash":{},"data":data}) : helper)))
    + "\">\n                    </div>\n                    <div class=\"form-group\" id=\"levelTwo_formGroup\">\n                        <div class=\"row\">\n                            <div class=\"col-6\"><label>二级系统分类</label></div>\n                            <div class=\"col-6 text-right\">\n                                <button class=\"btn btn-outline-success\" onclick=\"addLevelTwoInput()\" type=\"button\">\n                                    <i class=\"fa fa-plus-circle\"></i>\n                                </button>\n                            </div>\n                        </div>\n                        <div class=\"row\">\n                            <div class=\"col-10\">\n                                <input type=\"text\" class=\"form-control\" placeholder=\"二级系统分类\" name=\"levelTwoNameList\">\n                            </div>\n                            <div class=\"col-2 text-right\">\n\n                            </div>\n                        </div>\n                    </div>\n                </form>\n            </div>\n            <div class=\"modal-footer\">\n                <button type=\"button\" class=\"btn btn-outline-secondary\" data-dismiss=\"modal\">关闭</button>\n                <button type=\"button\" class=\"btn btn-outline-success\" onclick=\"confirmAdd()\">确认添加</button>\n            </div>\n        </div>\n    </div>\n</div>";
},"useData":true});
})();