(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['uploadVideo'] = template({"1":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "            <option value=\""
    + alias4(((helper = (helper = helpers.programId || (depth0 != null ? depth0.programId : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"programId","hash":{},"data":data}) : helper)))
    + "\">"
    + alias4(((helper = (helper = helpers.programName || (depth0 != null ? depth0.programName : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"programName","hash":{},"data":data}) : helper)))
    + "</option>\n";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1;

  return "<div class=\"container-fluid\">\n  <div class=\"row justify-content-around\">\n    <div class=\"col-11 mt-5 offset-1\">\n      <form>\n        <div class=\"form-group row mt-4\">\n          <label for=\"program\" class=\"col-md-3 col-form-label\">所属栏目</label>\n          <select class=\"form-control col-md-3\" id=\"programSelect\">\n            <option value=\"0\">--请选择--</option>\n"
    + ((stack1 = helpers.each.call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? depth0.programList : depth0),{"name":"each","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data})) != null ? stack1 : "")
    + "          </select>\n          <button type=\"button\" class=\"btn btn-outline-primary offset-1\">\n            创建栏目\n          </button>\n        </div>\n        <div class=\"form-group row\">\n          <label for=\"videoTitle\" class=\"col-md-3 col-form-label\">视频标题</label>\n          <input type=\"text\" class=\"form-control col-md-5\" id=\"videoTitle\" />\n        </div>\n        <div class=\"form-group row\">\n          <label for=\"videoTitle\" class=\"col-md-3 col-form-label\">视频序号</label>\n          <input type=\"text\" class=\"form-control col-md-5\" id=\"videoIndex\" />\n        </div>\n        <div class=\"form-group row mt-4\">\n          <label for=\"formControlFile1\" class=\"col-md-3 col-form-label\">上传视频</label>\n          <input type=\"file\" class=\"form-control-file col-md-5\" id=\"videoFile\" style=\"padding-left:0%\" />\n        </div>\n        <div class=\"form-group row mt-4\">\n          <label for=\"approvalOpinion\" class=\"col-md-3 col-form-label\">面向审批人备注</label>\n          <textarea class=\"form-control col-md-5\" rows=\"5\" id=\"approvalOpinion\"></textarea>\n        </div>\n\n        <button id=\"submitButton\" type=\"button\" class=\"btn btn-primary offset-md-3 mt-5\">\n          确认发布\n        </button>\n      </form>\n    </div>\n  </div>\n</div>\n\n<script>\n  $(function () {\n\n    $(\"#submitButton\").click(function () {\n      let parameterData = new FormData();\n      parameterData.append(\"videoFile\",$(\"#videoFile\")[0].files[0]);\n      parameterData.append(\"programId\",$('#programSelect').val());\n      parameterData.append(\"videoTitle\",$('#videoTitle').val());\n      parameterData.append(\"videoIndex\",parseInt($('#videoIndex').val()));\n      parameterData.append(\"opinion\",$('#approvalOpinion').val());\n      \n      $.ajax({\n        xhrFields: { withCredentials: true },\n        type: \"post\",\n        url: \"http://127.0.0.1:8080/STE/uploadVideo\",\n        processData: false, //不处理发送的数据\n        contentType: false, //不设置Content-Type请求头\n        data: parameterData,\n        success: function (data) {\n          console.log(data);\n        },\n        error: function (data) {\n          alert(data);\n        }\n      });\n    });\n\n  });\n</script>\n\n";
},"useData":true});
})();